<?php

function kg_galerie_photos_preprocess_field(&$variables) {
  if($variables['element']['#bundle'] == 'gallery' && $variables['element']['#field_name'] == 'field_gallery_pictures'){
    //@todo définir comme admin form settings
    $classnames = array('fancybox');
    foreach($variables['items'] as $key => &$item){
      $item['#item']['alt'] = $item['#item']['title'];
      $item['#path']['options'] = array('attributes'=>array('class'=>$classnames,'rel'=>$variables['element']['#object']->title));
    }
  }
}